chapter3review/taskleaf/config/routes.rb
Rails.application.routes.draw do
	root to: 'tasks#index'
	resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

chapter3review/taskleaf/app/models/task.rb
class Task < ApplicationRecord
end

chapter3review/taskleaf/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
	@tasks = Task.all
  end

  def show
	@task = Task.find(params[:id])
  end

  def new
	@task = Task.new
  end

  def create
	task = Task.new(task_params)
	task.save!
	redirect_to(tasks_url, notice: "registered task, [#{task.name}]")
	# flash[:notice] = 'sentence'
	# redirect_to(tasks_url)これと一緒
  end

  def edit
	@task = Task.find(params[:id])
  end

  def update
	task = Task.find(params[:id])
	task.update!(task_params)
	redirect_to tasks_url, notice: "updated task #{task.name}."
  end

  def destroy
	task = Task.find(params[:id])
	task.destroy
	redirect_to tasks_url, notice: "Successfully deleted task #{task.name}."
  end

  private

  def task_params
	params.require(:task).permit(:name, :description)
	# パラメータに含まれる"task"キーに対応するバリューを取得し、name, descriptionがあるときだけ取得
  end
end

chapter3review/taskleaf/app/helpers/tasks_helper.rb
module TasksHelper
end

chapter3review/taskleaf/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Taskleaf
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
	.app-title.navbar.navbar-expand-md.navbar-light.bg-light
		.navbar-brand Taskleaf
	.container
		- if flash.notice.present?
			.alert.alert-success= flash.notice
		= yield

chapter3review/taskleaf/app/views/tasks/_form.html.slim
= form_with model: task, local: true do |f|
	.form-group
		= f.label :name
		= f.text_field :name, class: 'form-control', id: 'task_name'
	.form-group
		= f.label :description
		= f.text_field :description, rows: 5, class: 'form-control', id: 'task_description'
	= f.submit nil, class: 'btn btn-primary'

chapter3review/taskleaf/app/views/tasks/edit.html.slim
h1 Tasks#edit

.nav.justify-content-end
	= link_to 'list', tasks_path, class: 'nav-link'

= render partial: 'form', locals: {task: @task}
/ p Find me in app/views/tasks/edit.html.slim

chapter3review/taskleaf/app/views/tasks/index.html.slim
h1 Tasks#index
= link_to 'register new task!', new_task_path, class: 'btn btn-primary'
/ <a href=new_task_path>bunsyou</a>

.mb-3
table.table.table-hover
	thead.thead-default
		tr
			th= Task.human_attribute_name(:name)
			th= Task.human_attribute_name(:created_at)
	tbody
		- @tasks.each do |task|
			tr
				td= link_to task.name, task_path(task)
				td= task.created_at
				td
					= link_to 'edit page', edit_task_path(task), class: 'btn btn-primary mr-3'
					= link_to 'delete', task, method: :delete, data: {confirm: "Is it OK to delete task #{task.name}?"}, class: 'btn btn-danger'

/ p Find me in app/views/tasks/index.html.slim

chapter3review/taskleaf/app/views/tasks/new.html.slim
h1 Tasks#new

.nav.justify-content-end
	= link_to "task list page", tasks_path, class: 'nav-link'

= render partial: 'form', locals: {task: @task}
	//TODO: なぜこれでcreateアクションに飛ぶのかわからない

/ p Find me in app/views/tasks/new.html.slim

chapter3review/taskleaf/app/views/tasks/show.html.slim
h1 Tasks#show

.nav.justify-content-end
	= link_to 'list', tasks_path, class: 'nav-link'
table.table.table-hover
	tbody
		tr
			th= Task.human_attribute_name(:id)
			td= @task.id
		tr
			th= Task.human_attribute_name(:name)
			td= @task.name
		tr
			th= Task.human_attribute_name(:description)
			td= simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div")
		tr
			th= Task.human_attribute_name(:created_at)
			td= @task.created_at
		tr
			th= Task.human_attribute_name(:updated_at)
			td= @task.updated_at
= link_to 'edit page', edit_task_path, class: 'btn btn-primary mr-3'
= link_to 'delete', @task, method: :delete, data: {confirm: "Is it OK to delete task #{@task.name}?"}, class: 'btn btn-danger'
/ p Find me in app/views/tasks/show.html.slim